version: '3'
services:
  api:
    build: ./api
    ports:
      - "3333:3333"
  frontend:
    build: ./front-end
    ports:
      - "3000:80"
  cdk:
    build: ./cdk
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}